import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_Component/Navbar/Navbar";
import Footer from "./_Component/Footer/Footer";

import bgImage from "_/images/light-patten.svg"
import { Toaster } from "_/components/ui/sonner";
import MySessionProvider from "./_Component/MySessionProvider/MySessionProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        style={{backgroundImage:`url(${bgImage.src})`}}
      >

          <MySessionProvider>

          <Navbar/>
          <div className="min-h-screen mt-20">
            {children}
          </div>
          <Toaster/>
          <Footer/>

          </MySessionProvider>

      </body>
    </html>
  );
}
