"use client"
import React, { ReactNode, useContext } from 'react'
import { Toaster } from "./../../../components/ui/sonner";
import Footer from "./../Footer/Footer";
import Navbar from "../../_Component/Navbar/Navbar";
import { CartContext } from '../MySessionProvider/CartContext';
import { Geist, Geist_Mono } from 'next/font/google';
import { Metadata } from 'next';
import bgImage from "_/images/light-patten.svg"
import MySessionProvider from '../MySessionProvider/MySessionProvider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function AppBody({children}:{children : ReactNode}) {
  
    let {dark} =useContext(CartContext);
    // console.log(dark);
    


    return (
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${dark ? "dark":""}  transition-all duration-500 `}
        style={{backgroundImage:`url(${bgImage.src})`}}
      >
          
          <Navbar/>
          <div className="min-h-screen mt-20">
            {children}
          </div>
          <Toaster/>
          <Footer/>


      </body>
  )
}
